name: EU ZPS Backup and Restore

on:
 workflow_dispatch:
   inputs:
     env:
      description: "Please provide the environments to restore: uat-eu, dev-eu"
      required: true
     dbName:
       description: "Please slecte the db to be restored"
       required: true
       type: choice
       options:
        - zps

jobs:
  Backup_Restore: 
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repository
       uses: actions/checkout@v2
       with:
           fetch-depth: 0
       
     - name: Eu ZPS Backup and Restore
       run: |
         echo "Taking the dump from Eu ZPS."
         bash zps_eu-mongo-backup-restore.sh
       env:
        env: ${{ inputs.env }}
        dbName: ${{ inputs.dbName }}
