name: EU ZPS Backup and Restore

on:
 workflow_dispatch:
   inputs:
     env:
      description: "Please provide the environments to restore: uat-eu, dev-eu"
      required: true
     dbNames:
       description: "Please slecte the db to be restored"
       required: true
       type: choice
       options:
        - zps

jobs:
  Backup_Restore: 
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repository
       uses: actions/checkout@v2
       with:
           fetch-depth: 0
       
     - name: Eu ZPS Backup and Restore
       run: |
         echo "Taking the dump from Eu ZPS."
         bash zps_eu-mongo-backup-restore.sh
       env:
        env: ${{ inputs.env }}
        dbNames: ${{ inputs.dbNames }}
        collectionsToExclude: ${{ vars.COLLECTIONSTOEXCLUDE }}
        mongodb_user_uat_eu: ${{ secrets.MONGO_USER_UAT_EU }}
        mongodb_pass_uat_eu: ${{ secrets.MONGO_PASS_UAT_EU }}
        mongodb_user_dev_eu: ${{ secrets.MONGO_USER_UAT_EU }}
        mongodb_pass_dev_eu: ${{ secrets.MONGO_PASS_UAT_EU }}
        mongodb_api_pub_uat_eu: ${{ vars.MONGODB_API_PUB_UAT_EU }}
        mongodb_api_pvt_uat_eu: ${{ vars.MONGODB_API_PVT_UAT_EU }}
        mongodb_api_pub_dev_eu: ${{ vars.MONGODB_API_PUB_DEV_EU }}
        mongodb_api_pvt_dev_eu: ${{ vars.MONGODB_API_PVT_DEV_EU }}
        cidrblock_uat_eu: ${{ vars.CIDRBLOCK_UAT_EU }}
        natgw_uat_eu: ${{ vars.NATGW_UAT_EU }}
        groupid_uat_eu: ${{ vars.GROUPID_UAT_EU }}
        cidrblock_dev_eu: ${{ vars.CIDRBLOCK_DEV_EU }}
        natgw_dev_eu: ${{ vars.NATGW_DEV_EU }}
        groupid_dev_eu: ${{ vars.GROUPID_DEV_EU }}
