name: Parsing the variables
on:
  workflow_dispatch:
     inputs:
        cluster:
          description: "Select the cluster to take the dump from."
          type: choice
          required: true
          options:
             - PROD_EU
             - UAT_EU
        dbName:
          description: "Slecet the db to take the dump."
          type: choice
          required: true
          options:
              - zps
          

jobs:
  Dump:
    runs-on: ubuntu-latest
    steps:
      - name: Taking the dump
        run: |
             echo ${{ secrets[format('MONGO_USER_{0}', inputs.cluster)] }} | sed 's/./& /g'
            
