name: First Workflow
on:
 workflow_dispatch:
   inputs:
     Name: 
       description: Please enter your name
       required: true
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: First Step in First Job
        run: echo "Hello ${{ inputs.Name }}"
